#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*                linuxserver/gazee                   *
*                                                    *
*     https://hub.docker.com/r/linuxserver/gazee     *
*                                                    *
*    https://github.com/linuxserver/docker-gazee     *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
